name: gap_tasks

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  flutter_local_notifications: ^16.3.2
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true 